### ISSUE TITLE
Reuse error

### ISSUE THREAD

**Issue by Spider-scnu** [deepmind/neural-processes#4]
When I run the 'attentive_neural_process.ipynb', I got the mistakes as follows:

ValueError: Variable layer_3/kernel already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "<ipython-input-4-20f2577573c8>", line 28, in batch_mlp
    output, output_sizes[-1], name="layer_{}".format(i + 1))
  File "<ipython-input-6-a52e0030599a>", line 31, in __call__
    hidden = batch_mlp(encoder_input, self._output_sizes, "latent_encoder")
  File "<ipython-input-8-a2102227fa62>", line 58, in __call__
    prior = self._latent_encoder(context_x, context_y)

**Comment by hyunjik11** [comment]
This may have happened because you haven't reset the TF computation graph.
Try running `tf.reset_default_graph()` then re-running the code.
