### ISSUE TITLE
package version control

### ISSUE THREAD

**Issue by jinxu06** [deepmind/neural-processes#5]
1. For the latest version of matplotlib, set_facecolor rather than set_axis_bgcolor should be used in plot_functions?
2. We should move TensorFlow Distributions to TensorFlow Probability?
3. It might be better to add information about package versions in the documentation?

**Comment by hyunjik11** [comment]
Thank you for pointing this out. We've updated the README to include the version control information. For future versions of tensorflow or matplotlib, we would advise the user to modify the code according to their setup. If you would like to suppress the deprecation warnings by tensorflow, consider using the following code:
```
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' 
```
