### ISSUE TITLE
Question for latent encoder of attentive neural processes script

### ISSUE THREAD

**Issue by jsikyoon** [deepmind/neural-processes#6]
Hi,

First of all, thank you for opening your great script!

I have a question about latent encoder.

In your code, posterior and prior use same latent encoder. Exactly using same (x,y) pair encoder is no problem, but the linear layers to sample the latent variable would be different functions for prior and posterior I think. 

If my understanding about the code is wrong, then could I know which point I missed?

Thanks.

Best Regards,
Jaesik Yoon.

**Comment by hyunjik11** [comment]
Hi Jaesik, I'm not quite sure what you mean when you say
> linear layers to sample the latent variable would be different functions for prior and posterior

The code uses the same linear function for both; using the notation of Equation (3) in the Attentive Neural Processes paper, the prior corresponds to q(z|s_C) and the posterior corresponds to q(z|s_T), and the same encoder parameters are used to compute samples from each (as well as the KL between them).

**Comment by jsikyoon** [comment]
Ah, I missed the equation. Okay, thank you for quick reply :)

2019년 5월 12일 (일) 오전 2:39, hyunjik11 <notifications@github.com>님이 작성:
